<?xml version="1.0" encoding="utf-8"?>
<xsl:stylesheet version="1.0" xmlns:xsl="http://www.w3.org/1999/XSL/Transform" xmlns:fo="http://www.w3.org/1999/XSL/Format">
	<xsl:variable name="initial_bottom_pos">0.1</xsl:variable>
	<xsl:variable name="initial_left_pos">0</xsl:variable>
	<xsl:variable name="height_increment">0</xsl:variable>
	<xsl:variable name="width_increment">0</xsl:variable>
	<xsl:variable name="frame_width">20.00cm</xsl:variable>
	<xsl:variable name="frame_height">5.0cm</xsl:variable>
	<xsl:variable name="number_columns">1</xsl:variable>
	<xsl:variable name="max_frames">8</xsl:variable>

	<xsl:template match="/">
		<xsl:apply-templates select="lots"/>
	</xsl:template>

	<xsl:template match="lots">
		<document>
			<template pageSize="(20.00cm,5.0cm)"   leftMargin="0.2cm" rightMargin="0.2cm" topMargin="5.9cm" bottomMargin="0.0cm" title="Product Barcode" author="Generated by SnippetBucket.com">
				<pageTemplate id="all">
					<pageGraphics/>
					<xsl:apply-templates select="lot-line" mode="frames"/>
				</pageTemplate>
			</template>
			<stylesheet>
				<paraStyle name="nospace" fontName="Courier" fontSize="20" spaceBefore="0" spaceAfter="0" alignment="center"/>
				<blockTableStyle id="mytable">
					<blockBackground colorName="white" start="0,0" stop="0,0"/>
					<blockBackground colorName="lightgrey" start="1,0" stop="-1,0"/>
					<blockAlignment value="CENTER"/>
					<blockValign value="MIDDLE"/>
					<blockFont name="Helvetica-BoldOblique" size="14" start="0,0" stop="-1,0"/>
					<blockFont name="Helvetica" size="8" start="0,1" stop="-1,1"/>
					
				</blockTableStyle>
			</stylesheet>
			<story>
				<xsl:apply-templates select="lot-line" mode="story"/>
			</story>
		</document>
	</xsl:template>

	<xsl:template match="lot-line" mode="frames">
		<xsl:if test="position() &lt; $max_frames + 1">
			<frame break-before="page">
				<xsl:attribute name="width">
					<xsl:value-of select="$frame_width"/>
				</xsl:attribute>
				<xsl:attribute name="height">
					<xsl:value-of select="$frame_height"/>
				</xsl:attribute>
				<xsl:attribute name="x1">
					<xsl:value-of select="$initial_left_pos + ((position()-1) mod $number_columns) * $width_increment"/>
					<xsl:text>cm</xsl:text>
				</xsl:attribute>
				<xsl:attribute name="y1">
					<xsl:value-of select="$initial_bottom_pos - floor((position()-1) div $number_columns) * $height_increment"/>
					<xsl:text>cm</xsl:text>
				</xsl:attribute>
			</frame>
		</xsl:if>
	</xsl:template>

    <xsl:param name="pmaxChars" as="xs:integer" select="80"/>

	<xsl:template match="lot-line" mode="story">
        <blockTable style="mytable" colWidths="18.5cm" rowHeights="1.2cm">
            <tr>
                <td >
                    <barCode message="123456789">
                         <height>100mm</height>
                         <ean-13>
                            <xsl:value-of select="ean13" />
                         </ean-13>
                     </barCode> 
                    <para style="nospace"><xsl:value-of select="ean13"/></para>
                </td>
            </tr>
            <tr>
                <td>
                    <para style="nospace">Price: <xsl:value-of select="price"/></para>
                </td>
            </tr>
            <tr>
                <td>
                    <para style="nospace">Code:  <xsl:value-of select="code"/></para>
                </td>
            </tr>
        </blockTable>
        <pageBreak/>
    </xsl:template>
</xsl:stylesheet>
